### ISSUE TITLE
TypeOfClaim page

### ISSUE THREAD

**Issue by Pascoe121** [hmrc/claim-tax-refund-frontend#103]
### Scrum details
Story points: **3**

### Description
Remove old AreYouSelfAssessed page
Do the scaffolding, validation on blank and content for the TypeOfClaim page

### Content
Heading - What kind of tax refund do you want to claim?
Options - Self assessment / Pay As You Earn
Blank - Select the type of refund you want to claim
Summary - Type of refund you want to claim

### Todo/subtasks
- [x] Use g8Scaffold to create a optionPage called TypeOfClaim
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the TelephoneNumber page to this new page
- [x] Update relevant tests
