### ISSUE TITLE
How much incapacity benefit page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#106]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much incapacity benefit a user recieves on the tax year they are claiming for

### Todo/subtasks
- [ ] Use g8Scaffold to create a intPage called HowMuchIncapacityBenefit
- [ ] Add custom content for headings, title and validation 
- [ ] Use the navigator to route from the AnyIncapacityBenefit page when Yes is selected
- [ ] Update relevant tests
