### ISSUE TITLE
How much employment and support allowance page 

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#108]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much employment and support allowance a user recieves on the tax year they are claiming for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchEmploymentSupportAllowance
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyEmploymentSupportAllowance page when Yes is selected
- [x] Update relevant tests
