### ISSUE TITLE
How much state pension page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#110]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much state pension a user recieves on the tax year they are claiming for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchStatePension
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyStatePension page when Yes is selected
- [x] Update relevant tests
