### ISSUE TITLE
How much car benefits page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#118]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much car benefits a user recieves on the tax year they are claiming for. Use Currency Regex

### Todo/subtasks
- [x] Use g8Scaffold to create a stringPage called HowMuchCarBenefits
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyCarBenefits page when Yes is selected
- [x] Update relevant tests
