### ISSUE TITLE
How much rental income

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#120]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much rental income a user recieves on the tax year they are claiming for, use currency regex

### Todo/subtasks
- [x] Use g8Scaffold to create a stringPage called HowMuchRentalIncome
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyRentalIncome page when Yes is selected
- [x] Update relevant tests
