### ISSUE TITLE
How much bank or building society interest income page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#122]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much bank or building society interest income a user recieves on the tax year they are claiming for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchBankBuildingSocietyInterest
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyBankBuildingSocietyInterest page when Yes is selected
- [x] Update relevant tests
