### ISSUE TITLE
How much medical benefits page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#124]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much medical benefts a user recieves on the tax year they are claiming for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchMedicalBenefits
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyMedicalBenefits page when Yes is selected
- [x] Update relevant tests
