### ISSUE TITLE
 How much other income page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#126]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much other benefits a user recieves on the tax year they are claiming for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchOtherIncome
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyOtherIncome page when Yes is selected
- [x] Update relevant tests
