### ISSUE TITLE
Name of person being paid page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#159]
### Scrum details
Story points:  **2**

### Description
Creating a stringPage to ask the a user who will recieve the payment of the refund

### Todo/subtasks (delete if not appropriate
- [x] Create the page with g8Scaffold stringPage and call it PayeeName
- [x] Change content in the messages file from the default
- [x] Add validation for none empty and maxlength 
- [x] Link navigation from previous pages
