### ISSUE TITLE
Create name of person being paid page 

### ISSUE THREAD

**Issue by MatthewAlexanderBeck** [hmrc/claim-tax-refund-frontend#169]
### Scrum details
Story points: 2

### Description
Do the scaffolding, validation on blank and content for the 'name of the person being paid' page

### Todo/subtasks (delete if not appropriate
- [ ] Use g8Scaffold to create a stringPage called PayeeFullName
- [ ] Add custom content for headings, title and validation
- [ ] Use the navigator to route from WhereToSendPayment (other path)
- [ ] Update relevant tests

**Comment by oliverslade** [comment]
Duplicate
