### ISSUE TITLE
Create do they have a agent reference page

### ISSUE THREAD

**Issue by MatthewAlexanderBeck** [hmrc/claim-tax-refund-frontend#172]
### Scrum details
Story points: 2

### Description
Do the scaffolding, validation on blank and content for the 'do they have a agent reference' page

### Todo/subtasks (delete if not appropriate)
- [x] Use g8Scaffold to create a yesNoPage called AnyAgentRef
- [x] Add custom content for headings, title and validation
- [x] Update relevant tests
- [x] Add navigation
