### ISSUE TITLE
Remake who to make payment page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#173]
### Scrum details
Story points: 2

### Description
The current payment page has been made as a yesNoPage when it should actually be an optionPage.

### Todo/subtasks (delete if not appropriate
- [x] Delete all files that relate to the who to make payment to page
- [x] Use g8Scaffold to create a optionPage with the same name as before
- [x] Add custom content for headings, title and validation
- [x] Use the navigator to route from all previous pages
- [x] Update relevant tests
