### ISSUE TITLE
Create agent reference number page

### ISSUE THREAD

**Issue by MatthewAlexanderBeck** [hmrc/claim-tax-refund-frontend#174]
### Scrum details
Story points: 2

### Description
Do the scaffolding, validation on blank and content for the agent reference page' page
### Todo/subtasks (delete if not appropriate
- [ ] Use g8Scaffold to create a stringPage called AgentRegerenceNumber
- [ ] Add custom content for headings, title and validation
- [ ] Update relevant tests
- [ ] Add navigation
