### ISSUE TITLE
Create check your answers page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#180]
### Scrum details
Story points: 13

### Description
Do the backend and frontend work required for a user to see a dynamic summary of all the answers they have given and a link to go back and change them. They will then be given a custom journey depending on which answer they change.

### Todo/subtasks (delete if not appropriate
- [x] Create the check your answers helpers and sections to handle to logic of how the content is displayed
- [x] Have these dynamically displayed on a summary page depending on what the users have answered
- [ ] Use the navigator to define the user journeys in CheckMode
