### ISSUE TITLE
Are you Self Assessed page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#57]
### Scrum details
Story points: 
Jira ticket number: 

### Description
Creating, validating and adding content for the are you self assessed page

### Todo/subtasks
- [x] Use g8Scaffold to create a boolean view called AreYouSelfAssessed
- [x] Add custom validation message key for when its blank. 
**Given** I am on the AreYouSelfAsssessed page. 
**When** I dont select anything and click continue
**Then** I see "Select yes if you are in Self Assessment"
- [x] Add custom content for the title and heading
- [x] Use the navigator to route from the Telephone Number page to this new page

### References or related material
Any attachments or links to PR's etc
