### ISSUE TITLE
UTR Page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#59]
### Scrum details
Story points: 
Jira ticket number: 

### Description
Do the scaffolding, validation using regex and content for the UTR page 

### Todo/subtasks (delete if not appropriate
- [x] Use g8Scaffold to create a stringPage called UniqueTaxpayerReference
- [x] Use regex to validate that a correct UTR has been entered
- [x] Add custom content for headings, title and validation

**Comment by Pascoe121** [comment]
Possible UTR regex? 
"/^[0-9A-Za-z]{1,10}$/"

**Comment by oliverslade** [comment]
Missing hint text from view. Reopening issue
