### ISSUE TITLE
Branch coverage is unusually low

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#69]
### Scrum
Story points: **3**

### Description
Our scoverage branch coverage is really low but there doesnt seem to be an explainable reason why it is that low. We need to do an investigation on why it is so low and then action any way we can find to improve it.

### Todo
- [ ] Fully understand how branch coverage is calculated, @garethgooch may have a head start on this one
- [ ] Identify any areas of our applications that are going untested
- [ ] Action/raise issues on how we can improve this coverage
