### ISSUE TITLE
PAYE Ref Page

### ISSUE THREAD

**Issue by Pascoe121** [hmrc/claim-tax-refund-frontend#72]
### Scrum details
Story points: 
Jira ticket number: 

### Description
Do the scaffolding, validation using regex and content for the PAYE Ref page 

### Todo/subtasks (delete if not appropriate
- [x] Use g8Scaffold to create a stringPage called PayAsYouEarn
- [x] Use regex to validate that a correct PAYE Ref has been entered
- [x] Add custom content for headings, title and validation 
- [x] Route from areYouSelfAssessed No 
- [x] Update relevant tests
- [x] Ensure view contains all relevent content
