### ISSUE TITLE
 Is your claim about a Self Assessment payment or credit page

### ISSUE THREAD

**Issue by Pascoe121** [hmrc/claim-tax-refund-frontend#73]
### Scrum details
Story points: **2**

### Description
Do the scaffolding, validation on blank and content for the SA debit / credit page 
Question : "Is your claim for a Self Assessment payment or credit?"

### Todo/subtasks
- [x] Use g8Scaffold to create a yesNoPage called SelfAssessmentClaim
- [ ] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the UTR page to this new page
- [x] Update relevant tests

**Comment by oliverslade** [comment]
Due to a redesign of the service we will no longer need this page. Closing the issue
