### ISSUE TITLE
Is it a full or partial claim page

### ISSUE THREAD

**Issue by Pascoe121** [hmrc/claim-tax-refund-frontend#74]
### Scrum details
Story points: **3**

### Description
Do the scaffolding, validation on blank and content for the Full Partial Claim page

#### Content
Heading - I want to claim: 
Radio 1 - All of the amount
Radio 2 - Some of the amount
**The radio buttons should be stacked vertically**

### Todo/subtasks
- [x] Use g8Scaffold to create a optionPage called FullOrPartialClaim
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the UTR page to this new page
- [x] Update relevant tests

**Comment by Pascoe121** [comment]
No longer doing due to change in design.
