### ISSUE TITLE
How much do you want to claim page

### ISSUE THREAD

**Issue by Pascoe121** [hmrc/claim-tax-refund-frontend#76]
### Scrum details
Story points: **3**

### Description
Do the scaffolding, validation on blank and content for the How Much page

### Content
Heading - How much do you want to claim?
Hint - Enter an amount that is the same or less than the amount you overpaid and include 2 decimal places, like 100.23

### Todo/subtasks
- [x] Use g8Scaffold to create a stringPage called PartialClaimAmount
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the FullOrPartialClaim page when some of it to this new page
- [x] Update relevant tests

**Comment by Pascoe121** [comment]
This is an int page so only allows to the nearest pound/whole numbers. Is this ok? Or should this be allowing a double. The current live form allows pence.
