### ISSUE TITLE
Select the tax year your claim relates to page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#90]
### Scrum details
Story points: **5**

### Description
This is a page with 4 radio buttons on it that allows the user to select one of the last 4 tax years that the claim relates to. These tax years need to dynamically update and be done using a nice pattern.

For example, when accessing the form today it shoud read:
- 6 April 2016 to 5 April 2017
- 6 April 2015 to 5 April 2016
- 6 April 2014 to 5 April 2015
- 6 April 2013 to 5 April 2014

### Todo/subtasks
- [x] Create an option page with g8Scaffold called TaxYearOfClaim
- [ ] Develop a way to dynamically update the last 4 tax years as shown above
- [x] Use the navigator to route from PayAsYouEarn page
