### ISSUE TITLE
How much jobseekers allowance page

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#96]
### Scrum details
Story points: **2**

### Description
Creating a stringPage to ask the user how much jobseekers allowance a user recieves on the tax year they are claiming for

### Content
Heading - How much Jobseeker's Allowance did you get during the tax year your claim is for?
Invalid Number - {see full partial claim}
Blank Number - {see full partial claim}
Check your answers label - Amount of Jobseeker's Allowance you got during the tax year your claim is for

### Todo/subtasks
- [x] Use g8Scaffold to create a intPage called HowMuchJobseekersAllowance
- [x] Add custom content for headings, title and validation 
- [x] Use the navigator to route from the AnyJobseekersAllowance page when Yes is selected
- [x] Update relevant tests
